// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCoreBulk.Data
{
    public partial class AdventureWorksDwbuildVersion
    {
        public string Dbversion { get; set; }
        public DateTime? VersionDate { get; set; }
    }
}