// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCoreBulk.Data
{
    public partial class DimScenario
    {
        public int ScenarioKey { get; set; }
        public string ScenarioName { get; set; }
    }
}